### ISSUE TITLE
[RFC] Make unit scales consistent

### ISSUE THREAD

**Issue by madeleineostoja** [tomorrowstudio/bloom#33]
Carrying on from #32, with a probable v3 breaking change coming it could be a good opportunity to rethink some fundamentals that Pollen blindly inherited from Tailwind. Namely, inconsistent unit scales.

We currently use:

- Numerical (eg: `--size-2`)
- Sizes (eg: `width-xs`)
- Descriptive (eg: `tracking-tight`).

If Pollen was to standardise on a scale I feel like it should be numeric, since that's the most obvious, extensible, and easiest to understand. 

Great discussion on Tailwind that was abandoned due to breaking change friction on a large project: https://github.com/tailwindlabs/tailwindcss/issues/1277

**Comment by crhallberg** [comment]
I agree that for line-height and border-radius making the values consistent is great. With the widths however, I feel that meaning is lost and incorrect meaning is implied (such that width-2 is half of width-4).

I think it would be better to have an alias for or otherwise emphasize commonly used breakpoints (768px, 544px, 1200px) and maybe tie the numbered units to something more immediately understandable. Best example for now: width-1 could be 10rem.

**Comment by madeleineostoja** [comment]
Hmm good point. I don't know that tying it to devices/breakpoints would be best, because you can't use CSS variables in breakpoints, the width scale is for setting max widths of containers on a page (for example). 

There are other places in Pollen where a numerical scale doesn't have the same proportional relationship as the Size scale, but I agree that widths are pretty closely tied to sizes, semantically, that it could be a gotcha. 

The only alternative I see is sticking to the original `xs` → `7xl` scale, but it feels a bit odd

**Comment by madeleineostoja** [comment]
yeah it's tricky. I guess we could reduce the width scale, I only ever use a few myself in the prod sites I've used Pollen on, and even then `measure` is usually a better tool for things like article max widths, and if anything it'd be worth expanding that scale. The current width scale was just lifted straight from Tailwind.
